### ISSUE TITLE
Could not allocate shared buffer for CUDA basecaller

### ISSUE THREAD

**Issue by ulbivin** [nanoporetech/megalodon#108]
Hello,

I am having some problems utilising my GPU for Megalodon. I run:
`megalodon /media/nano/Storage1/ONT_data/Cas9_enrich/K04_01022021/20210201_1218_MN35423_FAO96899_4d3a7685/fast5_pass --output-directory /media/nano/Storage1/ONT_data/Cas9_enrich/K04_01022021/20210201_1218_MN35423_FAO96899_4d3a7685/megalodon_gpu_test --guppy-server-path /opt/ont/guppy/bin/guppy_basecall_server --guppy-params "-d /home/nano/Programs/rerio/basecall_models/" --guppy-config res_dna_r941_min_modbases_5mC_CpG_v001.cfg --outputs basecalls mappings mod_mappings mods --reference /media/nano/Storage1/reference_seq/hg38/hg38.fa --mod-motif m CG 0 --overwrite --reads-per-guppy-batch 6 --guppy-timeout 30 --num-reads 100 --devices 0`
I run into a python error apperently when Megalodon attempts to disconnect from the basecall_server after timerout. 
```[13:55:38] Running Megalodon version 2.2.10
[13:55:38] Loading guppy basecalling backend
******************** WARNING: Guppy and pyguppy point versions do not match. This could lead to a failure. Install matching pyguppy version via `pip install ont-pyguppy-client-lib==4.4.2`. ********************
[2021-03-01 13:55:40.097555] [0x00007f80df0e1700] [info]    Connecting to server as 
Traceback (most recent call last):
  File "/home/nano/anaconda3/lib/python3.8/site-packages/megalodon/backends.py", line 630, in set_pyguppy_model_attributes
    init_called_read, _, _ = next(self.pyguppy_basecall(
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nano/anaconda3/bin/megalodon", line 8, in <module>
    sys.exit(_main())
  File "/home/nano/anaconda3/lib/python3.8/site-packages/megalodon/__main__.py", line 444, in _main
    megalodon._main(args)
  File "/home/nano/anaconda3/lib/python3.8/site-packages/megalodon/megalodon.py", line 1249, in _main
    model_info = backends.ModelInfo(backend_params, args.processes)
  File "/home/nano/anaconda3/lib/python3.8/site-packages/megalodon/backends.py", line 687, in __init__
    self._load_pyguppy()
  File "/home/nano/anaconda3/lib/python3.8/site-packages/megalodon/backends.py", line 678, in _load_pyguppy
    set_pyguppy_model_attributes()
  File "/home/nano/anaconda3/lib/python3.8/site-packages/megalodon/backends.py", line 650, in set_pyguppy_model_attributes
    self._pyguppy_client_disconnect()
  File "/home/nano/anaconda3/lib/python3.8/site-packages/megalodon/backends.py", line 521, in _pyguppy_client_disconnect
    self.client.disconnect()
AttributeError: 'NoneType' object has no attribute 'disconnect'
```

In the log.txt the Python script seems to disconnect as intended which is all good, but obviously does not resolve the GPU issue. Running the guppy_basecall_server from the command in log.txt seems to be running fine:
`/opt/ont/guppy/bin/guppy_basecall_server -p auto -l /media/nano/Storage1/ONT_data/Cas9_enrich/K04_01022021/20210201_1218_MN35423_FAO96899_4d3a7685/megalodon_gpu_test/guppy_log -c res_dna_r941_min_modbases_5mC_CpG_v001.cfg --post_out -x cuda:0 -d /home/nano/Programs/rerio/basecall_models/`
```
ONT Guppy basecall server software version 4.4.2+9623c1626, client-server API version 5.0.0
log path:            /media/nano/Storage1/ONT_data/Cas9_enrich/K04_01022021/20210201_1218_MN35423_FAO96899_4d3a7685/megalodon_gpu_test/guppy_log
chunk size:          2000
chunks per runner:   512
max queued reads:    2000
num basecallers:     4
num socket threads:  2
max returned events: 50000
gpu device:          cuda:0
kernel path:         
runners per device:  4


Config loaded:
config file:               /home/nano/Programs/rerio/basecall_models/res_dna_r941_min_modbases_5mC_CpG_v001.cfg
model file:                /home/nano/Programs/rerio/basecall_models/res_dna_r941_min_modbases_5mC_CpG_v001.jsn
model version id           None
adapter scaler model file: None

Starting server on port: 39347
```
GPU seems to be running CUDA just fine, and after running the command above it also has a pid running nvidia-smi:
```nvidia-smi
Mon Mar  1 14:03:30 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro P2200        On   | 00000000:65:00.0  On |                  N/A |
| 52%   47C    P0    23W /  75W |   3970MiB /  5056MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1171      G   /usr/lib/xorg/Xorg                250MiB |
|    0   N/A  N/A      1603      G   kwin_x11                           53MiB |
|    0   N/A  N/A      1609      G   /usr/bin/krunner                   47MiB |
|    0   N/A  N/A      1611      G   /usr/bin/plasmashell               68MiB |
|    0   N/A  N/A      2463      G   /usr/lib/firefox/firefox           47MiB |
|    0   N/A  N/A      5061      C   ...bin/guppy_basecall_server     3493MiB |
+-----------------------------------------------------------------------------+
```
Log files (renamed with .txt to enable upload):
[log.txt](https://github.com/nanoporetech/megalodon/files/6061928/log.txt)
[guppy_log.out.txt](https://github.com/nanoporetech/megalodon/files/6061932/guppy_log.out.txt)
[guppy_log.err.txt](https://github.com/nanoporetech/megalodon/files/6061933/guppy_log.err.txt)
[guppy_basecall_server_log-2021-03-01_13-55-38.log.txt](https://github.com/nanoporetech/megalodon/files/6061936/guppy_basecall_server_log-2021-03-01_13-55-38.log.txt)

Could you please suggest how to get Megalodon running on the GPU?

Kind regards,

Ulf

**Comment by marcus1487** [comment]
Could you try to install the matching pyguppy version? `pip install ont-pyguppy-client-lib==4.4.2`

**Comment by ulbivin** [comment]
Hi Marcus,

That solved the problem - thank you very much. I did try upgrading to 4.4.2 last week but it was not available at that time even though I got the warning message suggesting the update.

**Comment by ulbivin** [comment]
Hi again,

I don't know what is at play here, but it seems my problems are not solved after all. Besides not being able to run Megalodon on the GPU, I have since my post reinstalled MinKNOW in the GPU version (20.10.3) and I cannot run any live base calling while sequencing. Disabling this, the sequencing runs fine. It seems to be general problem with the guppy_basecall_server. Could you please suggest a solution to this or perhaps redirect me to the appropriate forum for guppy_basecall_server issues?

**Comment by ulbivin** [comment]
Just did that (downloaded v4.5.2 Linux 64-bit GPU tar.gz file) unzipped but get an error when running. Here from guppy_basecall_server_log-2021-04-08_16-38-37.log:
2021-04-08 16:38:37.975158 [guppy/message] ONT Guppy basecall server software version 4.5.2+bcc53d3, client-server API version 6.0.0
log path:            /media/nano/sda1/ONT_data/Cas9_enrich/K04_01022021/20210201_1218_MN35423_FAO96899_4d3a7685/megalodon_gpu_test_4/guppy_log
chunk size:          2000
chunks per runner:   512
max queued reads:    2000
num basecallers:     4
num socket threads:  2
max returned events: 50000
gpu device:          cuda:0
kernel path:         
runners per device:  4
2021-04-08 16:38:37.975351 [guppy/info] crashpad_handler not supported on this platform.
2021-04-08 16:38:37.975847 [guppy/info] Listening on port 38765.
2021-04-08 16:38:38.067285 [guppy/info] CUDA device 0 (compute 6.1) initialised, memory limit 5301600256B (4768333824B free)
2021-04-08 16:38:38.108510 [guppy/error] Substitution matrix for Minalign class must be 5x5.
2021-04-08 16:38:38.108564 [guppy/warning] An error occurred initialising the basecaller. Aborting.

**Comment by marcus1487** [comment]
This looks like a rerio bug introduced with Guppy 4.5.2. If you can do a `git pull` from the rerio repo it should resolve this issue.

**Comment by ulbivin** [comment]
Hi Marcus,
I did the git pull for the rerio update:
```
$ git pull https://github.com/nanoporetech/rerio
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 19 (delta 11), reused 14 (delta 6), pack-reused 0
Unpacking objects: 100% (19/19), done.
From https://github.com/nanoporetech/rerio
 * branch            HEAD       -> FETCH_HEAD
Updating 94baa67..e4190e3
Fast-forward
 README.rst                                               | 4 ++--
 basecall_models/barcoding/rerio_stub_mismatch_matrix.txt | 8 ++++++--
 basecall_models/res_dna_r103_min_crf_v032                | 1 +
 basecall_models/res_dna_r941_min_crf_v032                | 1 +
 4 files changed, 10 insertions(+), 4 deletions(-)
 create mode 100644 basecall_models/res_dna_r103_min_crf_v032
 create mode 100644 basecall_models/res_dna_r941_min_crf_v032
```
At first I got warning: ```WARNING: Guppy and pyguppy minor versions do not match. This may lead to a failure. Install matching pyguppy version via `pip install ont-pyguppy-client-lib==4.5.2```
So after installing ont-pyguppy-client-lib which also required downgrading numpy to 1.18.4, pyzmq to 17.1.2, pyqt5 to 5.12, and pyqtwebengine to 5.12, I ran
```$ megalodon /media/nano/sda1/ONT_data/Cas9_enrich/K04_01022021/20210201_1218_MN35423_FAO96899_4d3a7685/fast5_pass --output-directory /media/nano/sda1/ONT_data/Cas9_enrich/K04_01022021/20210201_1218_MN35423_FAO96899_4d3a7685/megalodon_gpu_test_4/ --guppy-server-path ~/Programs/ont-guppy/bin/guppy_basecall_server --guppy-params "-d /home/nano/Programs/rerio/basecall_models/" --guppy-config res_dna_r941_min_modbases_5mC_CpG_v001.cfg --outputs basecalls mappings mod_mappings mods --reference /media/nano/Storage1/reference_seq/hg38/hg38.fa --mod-motif m CG 0 --overwrite --reads-per-guppy-batch 6 --guppy-timeout 30 --num-reads 100 --devices 0```

Now I get this output:
```[09:30:09] Running Megalodon version 2.2.10
[09:30:09] Loading guppy basecalling backend
[2021-04-14 09:30:10.649099] [0x00007f38ef3ac700] [info]    Connecting to server as ''
[2021-04-14 09:30:10.651296] [0x00007f38ef3ac700] [info]    Connected to server as ''. Connection id: c68b5ca2-8fb6-4cc6-9614-6dbad941f559
[2021-04-14 09:30:18.681808] [0x00007f38ef3ac700] [info]    Connecting to server as ''
[2021-04-14 09:30:26.690468] [0x00007f38ef3ac700] [info]    Connecting to server as ''
...
```
Which seems to go on forever, occasionally with a timeout:
```
[2021-04-14 09:35:23.005586] [0x00007f38ef3ac700] [info]    Connection error. [timed_out] Timeout waiting for reply to request: LOAD_CONFIG
``` 
Any suggestions?

Log files (.txt added to filename):
[guppy_log.err.txt](https://github.com/nanoporetech/megalodon/files/6309833/guppy_log.err.txt)
[guppy_log.out.txt](https://github.com/nanoporetech/megalodon/files/6309834/guppy_log.out.txt)
[log.txt](https://github.com/nanoporetech/megalodon/files/6309836/log.txt)
[guppy_basecall_server_log-2021-04-14_09-56-23.log.txt](https://github.com/nanoporetech/megalodon/files/6309837/guppy_basecall_server_log-2021-04-14_09-56-23.log.txt)

**Comment by marcus1487** [comment]
The `Connecting to server as ''` is an issue with guppy/pyguppy. This has been logged internally and hopefully will be addressed in a release shortly.

This looks like the previous version of megalodon (<2.3). Could you try updating megalodon to the most recent version to see if the issue has been resolved with this latest release?

**Comment by ulbivin** [comment]
I've updatet Megalodon to version 2.3.1 but the issue remains. There seems to be some version conflicts between Megalodon and pyguppyclient (I have v.0.0.9). I also tried updating the latter and it downgrades ont-pyguppy-client-lib to v.4.4.1. However when I run Megalodon I get the warning:
```
WARNING: Guppy and pyguppy point versions do not match. This could lead to a failure. Install matching pyguppy version via `pip install ont-pyguppy-client-lib==4.5.2`
```
And again running the pip command I get:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyguppyclient 0.0.9 requires ont-pyguppy-client-lib==4.4.1, but you have ont-pyguppy-client-lib 4.5.2 which is incompatible.
Successfully installed ont-pyguppy-client-lib-4.5.2
```

**Comment by marcus1487** [comment]
Looks like you need to uninstall `pyguppyclient` which is no longer used in megalodon. Megalodon should still run even without this uninstallation though. Do you see errors when running megalodon now?

**Comment by ulbivin** [comment]
I deleted

**Comment by ulbivin** [comment]
I uninstalled pyguppyclient-0.0.9 (using pip). When running Megalodon:
```
$ megalodon /media/nano/sda1/ONT_data/Cas9_enrich/K04_01022021/20210201_1218_MN35423_FAO96899_4d3a7685/fast5_pass --output-directory /media/nano/sda1/ONT_data/Cas9_enrich/K04_01022021/20210201_1218_MN35423_FAO96899_4d3a7685/megalodon_gpu_test_4/ --guppy-server-path ~/Programs/ont-guppy/bin/guppy_basecall_server --guppy-params "-d /home/nano/Programs/rerio/basecall_models/" --guppy-config res_dna_r941_min_modbases_5mC_CpG_v001.cfg --outputs basecalls mappings mod_mappings mods --reference /media/nano/sda1/reference_seq/hg38/hg38.fa --mod-motif m CG 0 --overwrite --guppy-timeout 30 --num-reads 100 --devices 0
```
Screen output is the same as before:
```
[10:26:26] Running Megalodon version 2.3.1
[10:26:26] Loading guppy basecalling backend
[2021-04-16 10:26:28.036921] [0x00007fc49a7a8700] [info]    Connecting to server as ''
[2021-04-16 10:26:28.038659] [0x00007fc49a7a8700] [info]    Connected to server as ''. Connection id: 15ef2518-cf13-4c0d-b55e-f7f354f1caa2
[2021-04-16 10:26:36.064277] [0x00007fc49a7a8700] [info]    Connecting to server as ''
[2021-04-16 10:26:44.068836] [0x00007fc49a7a8700] [info]    Connecting to server as ''
```
And so on, but log.txt now quikcly contains 100ks of lines - here head and tail:
```
[10:26:26] Running Megalodon version 2.3.1
DBG 10:26:26 : Command: """/home/nano/anaconda3/bin/megalodon /media/nano/sda1/ONT_data/Cas9_enrich/K04_01022021/20210201_1218_MN35423_FAO96899_4d3a7685/fast5_pass --output-directory /media/nano/sda1/ONT_data/Cas9_enrich/K04_01022021/20210201_1218_MN35423_FAO96899_4d3a7685/megalodon_gpu_test_4/ --guppy-server-path /home/nano/Programs/ont-guppy/bin/guppy_basecall_server --guppy-params -d /home/nano/Programs/rerio/basecall_models/ --guppy-config res_dna_r941_min_modbases_5mC_CpG_v001.cfg --outputs basecalls mappings mod_mappings mods --reference /media/nano/sda1/reference_seq/hg38/hg38.fa --mod-motif m CG 0 --overwrite --guppy-timeout 30 --num-reads 100 --devices 0""" --- MainProcess-MainThread megalodon.py:1743
[10:26:26] Loading guppy basecalling backend
DBG 10:26:26 : Guppy version: "4.5.2" --- MainProcess-MainThread backends.py:828
DBG 10:26:26 : Pyguppy version: "4.5.2" --- MainProcess-MainThread backends.py:829
DBG 10:26:26 : guppy server init command: "/home/nano/Programs/ont-guppy/bin/guppy_basecall_server -p auto -l /media/nano/sda1/ONT_data/Cas9_enrich/K04_01022021/20210201_1218_MN35423_FAO96899_4d3a7685/megalodon_gpu_test_4/guppy_log -c res_dna_r941_min_modbases_5mC_CpG_v001.cfg --post_out --quiet -x cuda:0 -d /home/nano/Programs/rerio/basecall_models/" --- MainProcess-MainThread backends.py:904
DBG 10:26:26 : Found guppy log file: /media/nano/sda1/ONT_data/Cas9_enrich/K04_01022021/20210201_1218_MN35423_FAO96899_4d3a7685/megalodon_gpu_test_4/guppy_log/guppy_basecall_server_log-2021-04-16_10-26-26.log --- MainProcess-MainThread backends.py:919
DBG 10:26:28 : Connecting to server --- MainProcess-MainThread backends.py:776
DBG 10:26:36 : Get reads connection error  "Not connected to server. status code: status.preparing_connection. <super: <class 'PyGuppyClient'>, <PyGuppyClient object>>" --- MainProcess-MainThread backends.py:1051
DBG 10:26:36 : Get reads connection error  "Not connected to server. status code: status.loading_config. <super: <class 'PyGuppyClient'>, <PyGuppyClient object>>" --- MainProcess-MainThread backends.py:1051
DBG 10:26:36 : Get reads connection error  "Not connected to server. status code: status.loading_config. <super: <class 'PyGuppyClient'>, <PyGuppyClient object>>" --- MainProcess-MainThread backends.py:1051
...
DBG 10:26:58 : Get reads connection error  "Not connected to server. status code: status.loading_config. <super: <class 'PyGuppyClient'>, <PyGuppyClient object>>" --- MainProcess-MainThread backends.py:1051
DBG 10:26:58 : Get reads connection error  "Not connected to server. status code: status.loading_config. <super: <class 'PyGuppyClient'>, <PyGuppyClient object>>" --- MainProcess-MainThread backends.py:1051
DBG 10:26:58 : init_test_read BasecallingFailed Timeout --- MainProcess-MainThread backends.py:1079
```
Basecall server log:
[guppy_basecall_server_log-2021-04-16_10-26-26.log.txt](https://github.com/nanoporetech/megalodon/files/6323710/guppy_basecall_server_log-2021-04-16_10-26-26.log.txt)

Btw. initialising the basecall server with
```
/home/nano/Programs/ont-guppy/bin/guppy_basecall_server -p auto -l /media/nano/sda1/ONT_data/Cas9_enrich/K04_01022021/20210201_1218_MN35423_FAO96899_4d3a7685/megalodon_gpu_test_4/guppy_log -c res_dna_r941_min_modbases_5mC_CpG_v001.cfg --post_out --quiet -x cuda:0 -d /home/nano/Programs/rerio/basecall_models/
```
no longer gives me any screen output like in my first post - it is just blank until i terminate it.
```
$ nvidia-smi
```
does however show the process:
```
Fri Apr 16 10:43:14 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro P2200        On   | 00000000:65:00.0  On |                  N/A |
| 56%   55C    P0    23W /  75W |   4027MiB /  5056MiB |      5%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1405      G   /usr/lib/xorg/Xorg                249MiB |
|    0   N/A  N/A      2787      G   kwin_x11                           57MiB |
|    0   N/A  N/A      2792      G   /usr/bin/krunner                   47MiB |
|    0   N/A  N/A      2794      G   /usr/bin/plasmashell               71MiB |
|    0   N/A  N/A     15815      G   /usr/lib/firefox/firefox           47MiB |
|    0   N/A  N/A     17124      G   /usr/lib/firefox/firefox           47MiB |
|    0   N/A  N/A     17909      G   /usr/lib/firefox/firefox            1MiB |
|    0   N/A  N/A     35457      C   ...bin/guppy_basecall_server     3493MiB |
+-----------------------------------------------------------------------------+
```
and the basecall server log looks as before:
[guppy_basecall_server_log-2021-04-16_10-42-43.log.txt](https://github.com/nanoporetech/megalodon/files/6323741/guppy_basecall_server_log-2021-04-16_10-42-43.log.txt)

**Comment by ulbivin** [comment]
Everything is finally running! It took a reboot, which I have done several times along the way, so it must have been one of the recent actions above that fixed the problem, but at this point I am not sure which. However both Megalodon and live base calling and mapping in MinKNOW is now running on the GPU.
