### ISSUE TITLE
IO Bottleneck Issue

### ISSUE THREAD

**Issue by damioresegun** [nanoporetech/megalodon#176]
Hi, 
I'm sorry if this has been brought up before and resolved, if so, please do point me in the direction of the issue and I will attempt that. 
Now my issue: I'm trying out megalodon for the first time. I have read through the documentation and have thought I'd give it a go. 
The command I used was `megalodon --guppy-server-path ~/scratch/apps/ont-guppy/bin/guppy_basecall_server --outputs basecalls mod_basecalls mappings per_read_mods mods mod_mappings --reference ~/scratch/private/Index/Jan2020_PainReference/Pknowlesi_contigs.fasta --output-directory ~/scratch/private/PublicationAnal/methylation/ --overwrite ~/projects/uosa/Janet_Cox_Singh/dro/RawData/All_RawFiles/Dec_18_Data_2/dro48_18_141218_clinicals/dro48_18_141218_clinicals/20181215_1504_MN17366_FAH77786_ebd377ca/fast5/ --guppy-concurrent-reads 2 --processes 4`

To note: I am running this using megalodon v2.3.4 installed via conda and guppy v5.0.11+2b6dbff. 
I have also run this on a HPC cluster with a gpu node using  a Tesla V100 card with 16 GB of dedicated GPU memory

In all attempts that I have made, I am getting an IO issue: see image below.
![image](https://user-images.githubusercontent.com/33520829/127011036-61168360-9c11-4bd4-8749-3ddd523f1ca3.png)

Over the different iterations of the command I have done, the "input queue capacity extract_signal" value has only gone up to as high as 8%. 

I thought that considering it was an IO issue, perhaps if I gave it more memory, it should be fine so I attempted the same command with 32Gb of vRAM and no dice either. 

Any help would be highly appreciated.

**Comment by marcus1487** [comment]
It looks like there is an issue with the package which manages the progress bars (tqdm) in megalodon. It looks like the function raising the error here (`set_desciption_str`) was added in version 2.17 (2017). Could you check the version of tqdm being used (`python -c "import tqdm; print(tqdm.__version__)"`). If this is lower than 2.17 that would explain this bahavior. Upgrading (`pip install -U tqdm`) should resolve the issue. I will add this dependency version pin to ensure this does not happen to other users.

Hopefully this cleans up the progress output. I am guessing that the progress bars may not be updating after this error and that you may not actually have an IO issue. Please post if this resolves the issue and you are still experiencing IO issues. Briefly the options to look at tuning IO issues are `--num-read-enumeration-threads`, `--num-extract-signal-processes` (see `megalodon --help-long`).

**Comment by damioresegun** [comment]
Hi Marcus, 
Thanks for the speedy reply. I checked the tqdm as you described and it returned that it was v4.46.0. So I updated it anyway and then it updated to 4.61.2. Running the command again still generates the original issue.  The progress bar does appear to be working but somehow its throwing up the IO issue still. I went through the options you suggested to arrive at this command: 
`megalodon --guppy-server-path ~/scratch/apps/ont-guppy/bin/guppy_basecall_server --outputs basecalls mod_basecalls mappings per_read_mods mods mod_mappings --reference ~/scratch/private/Index/Jan2020_PainReference/Pknowlesi_contigs.fasta --output-directory ~/scratch/private/PublicationAnal/methylation/ --overwrite ~/projects/uosa/Janet_Cox_Singh/dro/RawData/All_RawFiles/Dec_18_Data_2/dro48_18_141218_clinicals/dro48_18_141218_clinicals/20181215_1504_MN17366_FAH77786_ebd377ca/fast5/ --guppy-concurrent-reads 1 --processes 1 --num-read-enumeration-threads 1 --num-extract-signal-processes 1` 

which also threw up the IO issue.

Do you think its possible that its saying that enough reads are not being inputted?

**Comment by marcus1487** [comment]
For the IO issue, I would recommend adding more read enumeration threads and extract signal processes. For example `--num-read-enumeration-threads 8 --num-extract-signal-processes 8`. Hopefully this will speed up the read extraction from disk. 

Note that this is not an issue of the amount of memory on GPU, but instead reading the data from disk into RAM. If your data are stored on a network file system it can help to transfer the data to a local fast (SSD) disk before running megalodon/guppy.

**Comment by damioresegun** [comment]
Hi Marcus,

Update:
I have tried adding the options as you suggested and ended up still getting the image below. Interestingly in this one, the tqdm is still an issue but megalodon seems to be running in the background. However a closer look into the log file showed that it kept failing and said there were timeouts. I've attached both log files. 

![image](https://user-images.githubusercontent.com/33520829/127045202-3233d538-f67f-4f9e-9d00-b90090def5a3.png)

In terms of the data reading speed, I'm running the gpu on a node as well as there is no way to run it locally as I don't have access to a local gpu unfortunately. Although I may be able to transfer the data to a faster partition. I'll look into it

**Comment by marcus1487** [comment]
This tqdm error is very confusing. I can't figure out how this might be happening. `tqdm` has had this attribute for many versions. It seems as though megalodon is somehow accessing a very old installation of `tqdm`. I'm not really sure how to address that issue.

For the disk IO, I would indeed suggest that you inquire local disk on node with your sys admin. The network file access is very likely the issue. This was the reason for adding the multiprocessing/threading flags noted, but sometimes the bandwidth is still too low.

**Comment by damioresegun** [comment]
Do you think installing from github might make tqdm work as it should?

Yeah, thanks for the suggestion. I will chase that up and update this as necessary once I know.

**Comment by damioresegun** [comment]
Hello, I'm back. I managed to move the data to the node's SSDs and ran it off there with the command below:
`megalodon --guppy-server-path ~/scratch/apps/ont-guppy/bin/guppy_basecall_server --outputs basecalls mod_basecalls mappings per_read_mods mods mod_mappings --reference ~/scratch/private/Index/Jan2020_PainReference/Pknowlesi_contigs.fasta --output-directory $TMPDIR/methylation/ --overwrite $TMPDIR/fast5/ --guppy-concurrent-reads 8 --processes 2 --num-read-enumeration-threads 8 --num-extract-signal-processes 8 --verbose-read-progress 10`

This still gave the same tqdm and IO error as above. I then also outputted it to the same SSDs and the same issue applies. 

So at this point, I'm not really sure how to proceed. Any advice? I've also added the log files
[log.txt](https://github.com/nanoporetech/megalodon/files/6886098/log.txt)
[guppy_basecall_server_log-2021-07-27_13-46-32.log](https://github.com/nanoporetech/megalodon/files/6886099/guppy_basecall_server_log-2021-07-27_13-46-32.log)

**Comment by damioresegun** [comment]
Further updates: I had a closer look at the log files and realised that it was running in CPU mode because somehow the `--devices` flag was lost at some point. However once that was added in (see command), I got the same basecaller_server error that was described in #171.
`megalodon --guppy-server-path ~/scratch/apps/ont-guppy/bin/guppy_basecall_server --outputs basecalls mod_basecalls mappings per_read_mods mods mod_mappings --reference ~/scratch/private/Index/Jan2020_PainReference/Pknowlesi_contigs.fasta --output-directory ~/scratch/private/PublicationAnal/methylation/ --overwrite ~/projects/uosa/Janet_Cox_Singh/dro/RawData/All_RawFiles/Dec_18_Data_2/dro48_18_141218_clinicals/dro48_18_141218_clinicals/20181215_1504_MN17366_FAH77786_ebd377ca/fast5/ --devices 0 --guppy-concurrent-reads 8 --processes 2 --num-read-enumeration-threads 4 --num-extract-signal-processes 4`

From this command I got this output (see image) and I have also attached the log files
![image](https://user-images.githubusercontent.com/33520829/127196784-94ddd18d-d383-488c-836c-adb7db002e24.png)

I ran the server initialising command as the error message suggested and all I get is "Killed" after the command was run. 

So from the looks of it, the server initiates in CPU mode but the IO is too slow, while the server doesn't even start in GPU mode? I definitely have the GPU version of Guppy installed though so I'm unsure why this would not work

[guppy_basecall_server_log-2021-07-27_18-02-35.log](https://github.com/nanoporetech/megalodon/files/6887446/guppy_basecall_server_log-2021-07-27_18-02-35.log)
[log.txt](https://github.com/nanoporetech/megalodon/files/6887447/log.txt)

**Comment by marcus1487** [comment]
This certainly quite odd. I think there are likely a couple different issues going on. I would recommend a re-installation in a fresh virtual environment (not a conda environment; We've seen some issues with environment variables set in conda core environments before). This can be done for example as:

```
python3.8 -m venv venv
source venv/bin/activate
pip install -U pip
pip install megalodon
```

Hopefully this can solve the tqdm error at a minimum and hopefully the failed basecall server init. 

On the IO error, could you elaborate on what you mean. Is there an actual error message? Or is this reads returning a timeout unsuccessful processing? Or something else?

**Comment by damioresegun** [comment]
I've done a fresh reinstall using both pip and Github. For pip, my python is v3.9 so I had to install python3.8 in a conda env and THEN do the megalodon installation you sent above. Installed just fine and activated the venv. However the same error command from my prior message (i.e. the message about the guppy backend not initialising). So no idea what to do with it now. 

At this point, I'm unsure if the IO error has been solved because I can't even get past the guppy basecall server initialising to reach a point where the reads would be read. 

So at this point, I think it is either that there is an odd bug in guppy basecaller server being initialised with a GPU or there is a thing with the cluster I'm working on. I've had a trawl of the open and closed issues and have come across a few with similar issues that I'm having so I'm not sure if it IS the cluster?

**Comment by marcus1487** [comment]
I've seen some unexpected behaviors related to conda when the base environment has been used to install lots of things. We've not been able to reproduce the behavior internally and so have not tracked down the exact root of the issue (likely an environment variable set by another conda package install). I would recommend either completely deactivating conda for this test or activating with the `--no-stack` option. If using conda python for the virtual environment you may need to change the virtual env init command to `python3.8 -m venv --copies venv`

**Comment by damioresegun** [comment]
Nope, no dice. Tried with no stacks and copies and still no initialisation. I'll keep trying to ask the sys admin if its something cluster based

**Comment by damioresegun** [comment]
Okay! So after many many commands, it seems like the issue was the "--gpu_runners_per_device" parameter for guppy. The default is 4 which apparently was too much. Setting it to 2 made the basecaller_server initialise. Success! 
However, next problem: server timeout. I have set the timeout to `--guppy-timeout 1000` but no dice. I've added a screenshot of the output. So what do you think?
![image](https://user-images.githubusercontent.com/33520829/127533542-7f290d4d-b398-4aff-8714-8c1d6869fe6b.png)

**Comment by marcus1487** [comment]
This screen shot is showing spam from the guppy clients. There is unfortunately no way to turn this off at the moment. Could you post your guppy log file to help diagnose this issue? It might also help if you could post the megalodon log file and the exact command that was run.

**Comment by damioresegun** [comment]
Sorry forgot to add those in. Here you go. Command:
megalodon /home/RawData/fast5/ --devices 0 --processes 8 --reference /home/Reference.fasta --outputs basecalls mappings mod_mappings mods --overwrite --output-directory /home/methylation/megal --guppy-server-path /home/ont-guppy/bin/guppy_basecall_server --guppy-params "--gpu_runners_per_device 2" --write-mods-text --num-read-enumeration-threads 8 --num-extract-signal-processes 8 --guppy-timeout 1000

[log.txt](https://github.com/nanoporetech/megalodon/files/6903579/log.txt)
[guppy_basecall_server_log-2021-07-29_17-35-43.log](https://github.com/nanoporetech/megalodon/files/6903580/guppy_basecall_server_log-2021-07-29_17-35-43.log)

**Comment by marcus1487** [comment]
For the log it looks like the IO issue has been resolved. And it also appears that the guppy server is initialized correctly (see copied lines below from the log, but now the guppy clients from megalodon cannot connect to the server. I would suggest checking the load on the node you are using if possible. There may be other jobs draining resources on the node and thus stalling the client from connecting to the guppy server. You could also try testing with a single process `--processes 1` to limit the number of connections.

Log entries showing valid guppy server init:
```
DBG 17:35:47 : pyguppy server status: result.success --- MainProcess-MainThread backends.py:840
DBG 17:35:47 : pyguppy server config: {'/mnt/shared/scratch/doresegu/apps/ont-guppy/data/dna_r9.4.1_450bps_modbases_5mc_hac.cfg': {'Basecalling': {'ModelFile': 'templa
DBG 17:35:47 : init_test_read BasecallingCompleted --- MainProcess-MainThread backends.py:1108
```

**Comment by damioresegun** [comment]
Yeah I can see that 50% of the gpu is being utilised currently. I'll see if I can get onto a free node. Is the 1000 timeout okay or should I let it go back to default?

**Comment by marcus1487** [comment]
The 1000 timeout is okay. This does not effect the client connection though. This is a parameter to indicate how long to wait for the server to return each read. After this timeout megalodon will move on and not process this read if it is ever returned from the server.

You might check that some of your previous attempts did not leave guppy servers in a zombie state. Certain exit conditions from megalodon fail to close the guppy server which can continue to consume GPU resources even after the megalodon call is complete. These jobs must be killed manually (I generally use `htop` to do so).
